node-exporter:
  persistence:
    host:
      enabled: true
      hostPath: /
      mountPath: /host
      readOnly: true
      setPermissions: false
      type: hostPath
    proc:
      enabled: false
    sys:
      enabled: false
  service:
    main:
      ports:
        metrics:
          port: 9100
          targetPort: metrics
          protocol: TCP
  workload:
    main:
      podSpec:
        containers:
          main:
            args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --web.listen-address=0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+|var/db/system/.+|mnt/[a-zA-Z0-9-_\\.]+/ix-applications/.+)($|/)
            - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
            - --collector.netdev.device-exclude=^veth.*$
            - --collector.netclass.ignored-devices=^veth.*$