node-exporter:
  persistence:
    host:
      enabled: true
      hostPath: /
      mountPath: /host
      readOnly: true
  service:
    main:
      ports:
        main:
          port: 9100
          targetPort: 9910
          protocol: http
